// <auto-generated>
// This file has been auto generated by EF Core Power Tools.
// </auto-generated>

#nullable disable

using System;
using System.Collections.Generic;

namespace Codesi.Factura.Persistencia.Models.Universidad;

public partial class Usuarios
{
    public int IdUsuario { get; set; }

    public string IdMicrosoft { get; set; }

    public string Email { get; set; }

    public string Nombre { get; set; }

    public string Cedula { get; set; }

    public string TipoPersona { get; set; }

    public bool Activo { get; set; }

    public DateTime FechaCreacion { get; set; }

    public virtual ICollection<Roles> IdRol { get; set; } = new List<Roles>();
}