// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Codesi.Factura.DemoConsola.Models;

public partial class categorias
{
    public int id_categoria { get; set; }

    public string nombre { get; set; }

    public virtual ICollection<productos> productos { get; set; } = new List<productos>();
}