// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Codesi.Factura.DemoConsola.Models;

public partial class clientes
{
    public int id_cliente { get; set; }

    public string tipo_identificacion { get; set; }

    public string identificacion { get; set; }

    public string razon_social { get; set; }

    public string direccion { get; set; }

    public string telefono { get; set; }

    public string email { get; set; }

    public virtual ICollection<facturas> facturas { get; set; } = new List<facturas>();
}