// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Codesi.Factura.DemoConsola.Models;

public partial class factura_pagos
{
    public int id_pago { get; set; }

    public int id_factura { get; set; }

    public string forma_pago { get; set; }

    public decimal total { get; set; }

    public virtual facturas id_facturaNavigation { get; set; }
}