// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Codesi.Factura.DemoConsola.Models;

public partial class licoreriaContext : DbContext
{
    public licoreriaContext()
    {
    }

    public licoreriaContext(DbContextOptions<licoreriaContext> options)
        : base(options)
    {
    }

    public virtual DbSet<categorias> categorias { get; set; }

    public virtual DbSet<clientes> clientes { get; set; }

    public virtual DbSet<factura_detalles> factura_detalles { get; set; }

    public virtual DbSet<factura_pagos> factura_pagos { get; set; }

    public virtual DbSet<facturas> facturas { get; set; }

    public virtual DbSet<productos> productos { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=(localdb)\\MSSQLLocalDB;Initial Catalog=licoreria;Integrated Security=True;Encrypt=True");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<categorias>(entity =>
        {
            entity.HasKey(e => e.id_categoria).HasName("PK__categori__CD54BC5AA5B5523F");

            entity.HasIndex(e => e.nombre, "UQ__categori__72AFBCC6D5EBA6CA").IsUnique();

            entity.Property(e => e.nombre)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
        });

        modelBuilder.Entity<clientes>(entity =>
        {
            entity.HasKey(e => e.id_cliente).HasName("PK__clientes__677F38F5190BE27F");

            entity.HasIndex(e => e.identificacion, "UQ__clientes__C196DEC765E7C982").IsUnique();

            entity.Property(e => e.direccion)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.email)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.identificacion)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.razon_social)
                .IsRequired()
                .HasMaxLength(200)
                .IsUnicode(false);
            entity.Property(e => e.telefono)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.tipo_identificacion)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
        });

        modelBuilder.Entity<factura_detalles>(entity =>
        {
            entity.HasKey(e => e.id_detalle).HasName("PK__factura___4F1332DEFD46FB3F");

            entity.Property(e => e.descuento)
                .HasDefaultValue(0.00m)
                .HasColumnType("decimal(10, 2)");
            entity.Property(e => e.precio_unitario).HasColumnType("decimal(10, 4)");
            entity.Property(e => e.subtotal).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.total).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.valor_iva).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.id_facturaNavigation).WithMany(p => p.factura_detalles)
                .HasForeignKey(d => d.id_factura)
                .HasConstraintName("FK__factura_d__id_fa__6477ECF3");

            entity.HasOne(d => d.id_productoNavigation).WithMany(p => p.factura_detalles)
                .HasForeignKey(d => d.id_producto)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__factura_d__id_pr__656C112C");
        });

        modelBuilder.Entity<factura_pagos>(entity =>
        {
            entity.HasKey(e => e.id_pago).HasName("PK__factura___0941B0740A72B29B");

            entity.Property(e => e.forma_pago)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.total).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.id_facturaNavigation).WithMany(p => p.factura_pagos)
                .HasForeignKey(d => d.id_factura)
                .HasConstraintName("FK__factura_p__id_fa__68487DD7");
        });

        modelBuilder.Entity<facturas>(entity =>
        {
            entity.HasKey(e => e.id_factura).HasName("PK__facturas__6C08ED5366AD884C");

            entity.HasIndex(e => e.clave_acceso, "UQ__facturas__46F7790D2F8714DA").IsUnique();

            entity.HasIndex(e => new { e.establecimiento, e.punto_emision, e.secuencial }, "uq_comprobante").IsUnique();

            entity.Property(e => e.clave_acceso)
                .HasMaxLength(49)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.establecimiento)
                .IsRequired()
                .HasMaxLength(3)
                .IsUnicode(false)
                .HasDefaultValue("001")
                .IsFixedLength();
            entity.Property(e => e.estado_sri)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValue("CREADA");
            entity.Property(e => e.fecha_emision)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.importe_total).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.propina)
                .HasDefaultValue(0.00m)
                .HasColumnType("decimal(10, 2)");
            entity.Property(e => e.punto_emision)
                .IsRequired()
                .HasMaxLength(3)
                .IsUnicode(false)
                .HasDefaultValue("001")
                .IsFixedLength();
            entity.Property(e => e.secuencial)
                .IsRequired()
                .HasMaxLength(9)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.subtotal_iva).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.subtotal_sin_impuestos).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.total_descuento)
                .HasDefaultValue(0.00m)
                .HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.id_clienteNavigation).WithMany(p => p.facturas)
                .HasForeignKey(d => d.id_cliente)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__facturas__id_cli__60A75C0F");
        });

        modelBuilder.Entity<productos>(entity =>
        {
            entity.HasKey(e => e.id_producto).HasName("PK__producto__FF341C0DA09D23CD");

            entity.HasIndex(e => e.codigo_principal, "UQ__producto__C7E95A9239EEC02D").IsUnique();

            entity.Property(e => e.activo).HasDefaultValue(true);
            entity.Property(e => e.codigo_principal)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.nombre)
                .IsRequired()
                .HasMaxLength(150)
                .IsUnicode(false);
            entity.Property(e => e.precio_unitario).HasColumnType("decimal(10, 4)");
            entity.Property(e => e.tarifa_iva)
                .HasDefaultValue(15.00m)
                .HasColumnType("decimal(5, 2)");

            entity.HasOne(d => d.id_categoriaNavigation).WithMany(p => p.productos)
                .HasForeignKey(d => d.id_categoria)
                .HasConstraintName("FK__productos__id_ca__5165187F");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}