// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Codesi.Factura.DemoConsola.Models;

public partial class productos
{
    public int id_producto { get; set; }

    public string codigo_principal { get; set; }

    public string nombre { get; set; }

    public decimal precio_unitario { get; set; }

    public int stock { get; set; }

    public decimal tarifa_iva { get; set; }

    public int? id_categoria { get; set; }

    public bool? activo { get; set; }

    public virtual ICollection<factura_detalles> factura_detalles { get; set; } = new List<factura_detalles>();

    public virtual categorias id_categoriaNavigation { get; set; }
}