// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Codesi.Factura.Persistencia.Models;

public partial class facturas
{
    public int id_factura { get; set; }

    public string establecimiento { get; set; }

    public string punto_emision { get; set; }

    public string secuencial { get; set; }

    public string clave_acceso { get; set; }

    public DateTime fecha_emision { get; set; }

    public int id_cliente { get; set; }

    public decimal subtotal_sin_impuestos { get; set; }

    public decimal? total_descuento { get; set; }

    public decimal subtotal_iva { get; set; }

    public decimal? propina { get; set; }

    public decimal importe_total { get; set; }

    public string estado_sri { get; set; }

    public virtual ICollection<factura_detalles> factura_detalles { get; set; } = new List<factura_detalles>();

    public virtual ICollection<factura_pagos> factura_pagos { get; set; } = new List<factura_pagos>();

    public virtual clientes id_clienteNavigation { get; set; }
}