// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Codesi.Factura.Persistencia.Models;

public partial class factura_detalles
{
    public int id_detalle { get; set; }

    public int id_factura { get; set; }

    public int id_producto { get; set; }

    public int cantidad { get; set; }

    public decimal precio_unitario { get; set; }

    public decimal? descuento { get; set; }

    public decimal subtotal { get; set; }

    public decimal valor_iva { get; set; }

    public decimal total { get; set; }

    public virtual facturas id_facturaNavigation { get; set; }

    public virtual productos id_productoNavigation { get; set; }
}